"""FJP v0.1 standard reason codes."""
from __future__ import annotations

import re

POLICY_SATISFIED = "POLICY_SATISFIED"
HARD_POLICY_VIOLATION = "HARD_POLICY_VIOLATION"
AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
EVIDENCE_MISSING = "EVIDENCE_MISSING"
RISK_THRESHOLD_EXCEEDED = "RISK_THRESHOLD_EXCEEDED"
FINANCIAL_THRESHOLD_EXCEEDED = "FINANCIAL_THRESHOLD_EXCEEDED"
HIGH_CONSEQUENCE_ACTION = "HIGH_CONSEQUENCE_ACTION"
HIGH_IRREVERSIBILITY = "HIGH_IRREVERSIBILITY"
INSUFFICIENT_CONFIDENCE = "INSUFFICIENT_CONFIDENCE"
CONFLICTING_RULES = "CONFLICTING_RULES"
USER_CONFIRMATION_REQUIRED = "USER_CONFIRMATION_REQUIRED"
HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
JUDGMENT_REQUIRED = "JUDGMENT_REQUIRED"
EVALUATION_FAILURE = "EVALUATION_FAILURE"

STANDARD = frozenset({
    POLICY_SATISFIED, HARD_POLICY_VIOLATION, AUTHORIZATION_FAILED, EVIDENCE_MISSING,
    RISK_THRESHOLD_EXCEEDED, FINANCIAL_THRESHOLD_EXCEEDED, HIGH_CONSEQUENCE_ACTION,
    HIGH_IRREVERSIBILITY, INSUFFICIENT_CONFIDENCE, CONFLICTING_RULES,
    USER_CONFIRMATION_REQUIRED, HUMAN_APPROVAL_REQUIRED, JUDGMENT_REQUIRED, EVALUATION_FAILURE,
})

# Custom codes: namespace.identifier, e.g. acme.vendor_credit_risk
CUSTOM_PATTERN = re.compile(r"^[a-z][a-z0-9_-]{0,63}\.[a-z0-9][a-z0-9_.-]{0,127}$")

# Escalations an automated resolver may NOT resolve by default: a human must.
NOT_AUTO_RESOLVABLE = frozenset({HUMAN_APPROVAL_REQUIRED, USER_CONFIRMATION_REQUIRED, EVALUATION_FAILURE})

DEFAULT_FOR_DECISION = {
    "ACT": POLICY_SATISFIED,
    "BLOCK": HARD_POLICY_VIOLATION,
    "ESCALATE": JUDGMENT_REQUIRED,
}


def is_valid(code: object) -> bool:
    return isinstance(code, str) and (code in STANDARD or bool(CUSTOM_PATTERN.match(code)))
