"""Regenerate conformance/fixtures/canonical.json from the Python reference implementation.

Every SDK must produce byte-identical canonical JSON and SHA-256 for these values.
Run: python scripts/gen_canonical_fixtures.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "python"))
from abe.canonical import canonical_json, hash_value  # noqa: E402

VALUES = [
    {"b": 1, "a": 2},
    {"amount": 12500, "currency": "USD", "type": "purchase"},
    {"x": 12500.0, "y": 0.91, "z": -0.0, "v": 1.5e-7, "u": 0.00001, "t": 123456789.125},
    {"nested": {"list": [3, 1, 2], "empty": {}, "arr": []}, "bool": [True, False, None]},
    {"s": "quote \" backslash \\ newline \n tab \t ctrl \u0001 unicode é 中文 emoji 😀 sep  "},
    {"é": 1, "e": 2, "E": 3, "😀": 4, "～": 5},
    [1, "two", {"three": 3}],
    "plain string",
    0.1,
    9007199254740991,
    {"t": "2026-09-29T16:00:00.5+02:00", "neg": -12.75, "tiny": 5e-324},
]

out = [{"value": v, "canonical": canonical_json(v), "hash": hash_value(v)} for v in VALUES]
path = os.path.join(os.path.dirname(__file__), "..", "conformance", "fixtures", "canonical.json")
with open(path, "w", encoding="utf-8") as fh:
    json.dump({"description": "Canonical JSON + SHA-256 parity vectors (generated by the Python SDK)",
               "vectors": out}, fh, ensure_ascii=False, indent=1)
    fh.write("\n")
print(f"wrote {len(out)} vectors to {os.path.normpath(path)}")
